# Generated by Django 5.1.4 on 2026-09-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="tickets/"),
        ),
    ]
