"""
Django settings for tickethub project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import ssl
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env только для локального запуска без Docker — в compose/на проде
# переменные задаёт сама платформа, .env туда не попадает (в .gitignore)
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-6)1t_ddd5lb_!p=u)7vz42o!5sc4=y$lmfmqe$^%2i%d0a8k9w"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [h for h in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h]

# для Django Admin на реальном домене — иначе POST с боевого хоста
# Django отклонит как подозрительный. Локально пусто, не мешает.
CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o
]

# прод-харденинг — только при DEBUG=False, иначе редирект на HTTPS
# сломает локальный docker compose (там всё по HTTP)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Render терминирует TLS на прокси и шлёт дальше по HTTP с этим
    # заголовком — без него Django уйдёт в бесконечный редирект на https
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 60 * 60 * 24


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "events",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # раздаёт статику прямо из gunicorn, без отдельного nginx —
    # обязательно сразу после SecurityMiddleware
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tickethub.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tickethub.wsgi.application"


# DATABASE_URL приходит из Docker Compose / платформы деплоя.
# Без неё — локальный sqlite, для быстрых экспериментов без поднятого Postgres.

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# CompressedManifestStaticFilesStorage требует, чтобы collectstatic уже
# отработал и создал манифест (bin/start-prod.sh делает это перед
# gunicorn) — локально collectstatic не запускается, поэтому включаем
# только в проде, иначе любой {% static %} упадёт с "не найден в манифесте"
if not DEBUG:
    STORAGES = {
        # MEDIA (PDF-билеты) — обычная файловая система, без изменений.
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        # Сжатая + версионированная (по хэшу в имени файла — безопасный
        # долгий Cache-Control) статика через WhiteNoise.
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# PDF-билеты (events/services.py) хранятся прямо на диске — для
# настоящего продакшена тут был бы S3, но для пет-проекта это лишнее
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# REDIS_URL используется и напрямую (SETNX для брони места), и как
# брокер/бэкенд Celery.
REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")

# сколько секунд держится место после SETNX — на это же значение
# ориентируется beat при чистке зависших HOLD в базе
SEAT_HOLD_TTL_SECONDS = int(os.environ.get("SEAT_HOLD_TTL_SECONDS", "300"))

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

CELERY_BEAT_SCHEDULE = {
    "release-expired-seat-holds": {
        "task": "events.tasks.release_expired_holds",
        "schedule": 60.0,
    },
}

# managed Redis (Upstash) отдаёт TLS-адрес rediss:// — redis-py сам его
# понимает для прямых подключений, а вот Celery нужно попросить явно
if REDIS_URL.startswith("rediss://"):
    CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": ssl.CERT_REQUIRED}
    CELERY_REDIS_BACKEND_USE_SSL = {"ssl_cert_reqs": ssl.CERT_REQUIRED}
