"""
Django settings for tickethub project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import ssl
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Локально без Docker переменные читаются из .env; в Docker Compose /
# на проде их задаёт сама платформа — .env туда просто не попадает
# (он в .gitignore), поэтому load_dotenv тут ничего не сломает.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-6)1t_ddd5lb_!p=u)7vz42o!5sc4=y$lmfmqe$^%2i%d0a8k9w"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [h for h in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h]

# Нужно для Django Admin (форм с CSRF) на реальном домене деплоя — без
# этого POST-запросы с боевого хоста Django отклоняет как подозрительные
# (Origin не совпадает ни с одним доверенным). Локально пусто — не мешает.
CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o
]

# Прод-харденинг (неделя 5): включаем только когда DEBUG=False, чтобы
# не мешать локальной разработке (там всё по HTTP, редирект на HTTPS
# сломал бы docker-compose). SECURE_PROXY_SSL_HEADER обязателен — Render
# (и большинство PaaS) терминирует TLS на своём прокси и проксирует
# дальше по обычному HTTP, добавляя заголовок X-Forwarded-Proto: без
# этой строки Django решит, что каждый запрос небезопасен, и уйдёт
# в бесконечный редирект на https.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    # Консервативное значение (1 день, без includeSubDomains) — HSTS
    # трудно откатить для реальных пользователей, если что-то пойдёт не
    # так с HTTPS; для пет-проекта с одним поддоменом этого достаточно.
    SECURE_HSTS_SECONDS = 60 * 60 * 24


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "events",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Отдаёт собранную статику (admin CSS/JS и т.п.) прямо из gunicorn-
    # процесса, без отдельного nginx — то, что нужно для однопроцессного
    # бесплатного деплоя (неделя 5). Должен идти сразу после
    # SecurityMiddleware — так требует сам WhiteNoise.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tickethub.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tickethub.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#
# DATABASE_URL приходит из Docker Compose / платформы деплоя
# (postgresql://user:pass@host:port/name). Без неё — локальный sqlite,
# чтобы `python manage.py check` и быстрые эксперименты работали
# без поднятого Postgres.

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Только для прод-режима (DEBUG=False): CompressedManifestStaticFilesStorage
# требует, чтобы collectstatic уже отработал и создал манифест хэшей
# файлов (это делает bin/start-prod.sh перед стартом gunicorn) — иначе
# любой {% static %} в шаблоне (например, в самой Django Admin) упадёт
# с ошибкой "не найден в манифесте". Локально collectstatic никогда не
# запускается (dev-сервер сам раздаёт статику как есть), поэтому здесь
# оставляем стандартное поведение Django, чтобы не сломать `docker
# compose up`.
if not DEBUG:
    STORAGES = {
        # MEDIA (PDF-билеты) — обычная файловая система, без изменений.
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        # Сжатая + версионированная (по хэшу в имени файла — безопасный
        # долгий Cache-Control) статика через WhiteNoise.
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Сгенерированные PDF-билеты (неделя 4, events/services.py). В деве и
# в этом дев-контейнере хранятся прямо на диске — для реального продакшена
# сюда бы встал S3-совместимый storage, но для пет-проекта это лишнее.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Redis + Celery (неделя 3: блокировка мест, фоновая очистка просроченных
# холдов). REDIS_URL используется и напрямую (events/redis_client.py —
# SETNX для брони места), и как брокер/бэкенд Celery.

REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")

# На сколько секунд удерживается место после успешного SETNX в Redis —
# и на этот же интервал ориентируется Celery beat при чистке зависших
# HOLD-заказов в базе (единый источник правды для обоих механизмов).
SEAT_HOLD_TTL_SECONDS = int(os.environ.get("SEAT_HOLD_TTL_SECONDS", "300"))

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

CELERY_BEAT_SCHEDULE = {
    "release-expired-seat-holds": {
        "task": "events.tasks.release_expired_holds",
        "schedule": 60.0,  # раз в минуту — см. диаграмму в README
    },
}

# Managed Redis (например, Upstash — неделя 5) отдаёт TLS-адрес
# rediss://; redis-py сам понимает эту схему для прямых подключений
# (events/redis_client.py), а вот Celery для транспорта на Redis нужно
# явно попросить SSL, иначе брокер не подключится.
if REDIS_URL.startswith("rediss://"):
    CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": ssl.CERT_REQUIRED}
    CELERY_REDIS_BACKEND_USE_SSL = {"ssl_cert_reqs": ssl.CERT_REQUIRED}
